### ISSUE TITLE
Role based access control

### ISSUE THREAD

**Issue by prafullmaru** [prafullmaru/ePanchayat#35]
Let us set-up login group for various category to manage permission better and grant access to different category with specific rights.
Ex- 
Developer-R-W
Developer-RO
Admin
User

**Comment by RiteshKolhe** [comment]
Hi Prafull,
I have created the below logins group and users. so we need to add the members in only AD group login, we don't need to create the new logins and users, also it will be standard and easy to manage the permission on group instead of particular users.

List of logins and users that created
1. ePanchayatAdmin => Granted full access (DDL, DML ,Read)
2. ePanchayatAppUser=> Granted read and write access ( DML ,Read)
3. ePanchayatDeveloper_R_W=> Granted read and write access ( DML ,Read)
4. ePanchayatDeveloper_Read_only=> Granted only read access (Read)

**Comment by prafullmaru** [comment]
@RiteshKolhe - This will be good to start. Will you please submit your changes and raise pull request?

**Comment by RiteshKolhe** [comment]
I have raised the PR with the db script changes, please check once.
https://github.com/prafullmaru/ePanchayat/pull/41
